### ISSUE TITLE
Unable to install - make modules showing error

### ISSUE THREAD

**Issue by SaiHarshaK** [KVM-VMI/kvm-vmi#100]
Hello, i followed Option 2 in the [setup guide](https://kvm-vmi.github.io/kvm-vmi/master/setup.html#kvm) but I have encountered the following error:
```
$ make -j4 modules
  DESCEND  objtool
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  Building modules, stage 2.
  MODPOST 4921 modules
ERROR: "unlock_device_hotplug" [drivers/dax/kmem.ko] undefined!
ERROR: "add_memory_resource" [drivers/dax/kmem.ko] undefined!
ERROR: "lock_device_hotplug" [drivers/dax/kmem.ko] undefined!
scripts/Makefile.modpost:93: recipe for target '__modpost' failed
make[1]: *** [__modpost] Error 1
Makefile:1280: recipe for target 'modules' failed
make: *** [modules] Error 2
```

Any suggestions on how I could resolve this? I am currently using Ubuntu 18.04.5 LTS

**Comment by SaiHarshaK** [comment]
Thanks for responding, i assumed the .config file generated from `$ make menuconfig` is enough to add those configurations.
I am able to complete the setup now.

Although, uname -a shows 5.4.24+ instead of 5.4.24-kvmi as written in doc.

**Comment by Wenzel** [comment]
> Although, uname -a shows 5.4.24+ instead of 5.4.24-kvmi as written in doc.

The `-kvmi` is a prefix that is being inserted in the [Makefile](https://github.com/KVM-VMI/kvm-vmi/blob/master/vagrant/ansible/roles/kvm/tasks/main.yml#L60) (vagrant-based setup).

I will fix the documentation for the Bare-Metal setup.

Thanks !

**Comment by panicos** [comment]
Hi, thank you for creating these libraries and patches.

I am trying to follow your bare metal guide. 
I have downloaded your kvm-tags-kvm-5.7-2 kernel and I run the following commands to build the kernel config.

```
make olddefconfig
./scripts/config --enable KVM
./scripts/config --enable KVM_INTEL
./scripts/config --enable KVM_AMD
./scripts/config --enable KVM_INTROSPECTION
./scripts/config --disable TRANSPARENT_HUGEPAGE
./scripts/config --enable REMOTE_MAPPING
```

When I run the `make -j4 bzImage` cmd my .config file (find it attached) gets overwritten by the makefile and the KVM_INTROSPECTION and REMOTE_MAPPING flaqs get removed. From my understanding this happens because for some reason the makefile believes my config is invalid.

My system has the following configuration 5.4.0-42-generic #46~18.04.1-Ubuntu SMP.
[panicos_config.txt](https://github.com/KVM-VMI/kvm-vmi/files/6575914/panicos_config.txt)


Do you know what I am going wrong here?

**Comment by Wenzel** [comment]
hi 

> I have downloaded your kvm-tags-kvm-5.7-2 kernel

there is no such tag un the kvm submodule.
you need to use the specific kvm commit that we have versioned from kvm-vmi root repo, otherwise you won't have VMI patches.

**Comment by panicos** [comment]
Hi, I was referring to the github.com/KVM-VMI/kvm project. Apologies if this issue is the wrong place to ask a question on this.

**Comment by Wenzel** [comment]
@panicos you are referring to the right repo, but on the wrong commit.

You can't just pick any commit you want.
You need to use the `kvmi-v7` branch, which is the KVM fork with VMI patches.
The latest commit of this branch is tracked by the kvm submodule.

**Comment by panicos** [comment]
OK I get you. Thank you for the quick response!

**Comment by Wenzel** [comment]
Sure, but next time open a new issue.
thanks
