### ISSUE TITLE
a question about the realization of the nitro 

### ISSUE THREAD

**Issue by Lixiaomingg** [KVM-VMI/kvm-vmi#18]
Hi, i have read the paper "Nitro: Hardware-based System Call Tracing for Virtual Machines" and i have a little question that how to trace the system calling in the code .
Could you tell me which code file which i should read ?
Thanks !

**Comment by Wenzel** [comment]
Hi,
could you please be more specific ?
What are you looking for ?

**Comment by Lixiaomingg** [comment]
HI ,
I want to know how the code about tracing the system calling  is written.
Could you give me some suggestion ? for example, which code file should i read?
Thanks

**Comment by Wenzel** [comment]
Nitro is mainly composed of 2 parts.
- KVM code modification
- Nitro userland library to listen and interpret system calls.

If you read the paper, you understood how the VM is tricked into exiting back to the hypervisor when a syscall/sysexit instruction is executed.

I think what you are looking for is what do we do in KVM at this moment.
Well, take a look at the exception handler, because that's where it begins:
https://github.com/KVM-VMI/kvm/blob/vmi/arch/x86/kvm/vmx.c#L5480

We are handling two cases:
- when we get a UD: https://github.com/KVM-VMI/kvm/blob/vmi/arch/x86/kvm/vmx.c#L5503
- when we get a GP: https://github.com/KVM-VMI/kvm/blob/vmi/arch/x86/kvm/vmx.c#L5518

The logic is the same for both as the instruction is going to be emulated, and the rest of the logic is in emulate.c.
https://github.com/KVM-VMI/kvm/blob/vmi/arch/x86/kvm/emulate.c
these functions are called to emulate a syscall
https://github.com/KVM-VMI/kvm/blob/vmi/arch/x86/kvm/emulate.c#L2622

and emulate a sysexit:
https://github.com/KVM-VMI/kvm/blob/vmi/arch/x86/kvm/emulate.c#L2832

we use that moment to set an event, which is blocking the VCPU execution until the userland Nitro library has received and processed it.

If you have other questions, feel free.

**Comment by Lixiaomingg** [comment]
Thanks for you suggestion !

**Comment by bigbigbanana** [comment]
Hello,in nitro sub-directory,i am a little confused about setup test vm,can i directly use virt-manager to create win7 test vm?

**Comment by Wenzel** [comment]
@bigbigbanana please do no hijack other people issue.
This is the second time already and it's really annoying for everyone, so please stop that.
