### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by shlomopongartz** [KVM-VMI/kvm-vmi#2]
Hi,
I've got the following build error.

shlomo@cloud-security1:~/nitro/KVM-VMI/kvm-vmi$ make modules
cd kvm && \
	make SUBDIRS=arch/x86/kvm modules
make[1]: Entering directory '/home/shlomo/nitro/KVM-VMI/kvm-vmi/kvm'

  WARNING: Symbol version dump ./Module.symvers
           is missing; modules will have no dependencies and modversions.

  CC [M]  arch/x86/kvm/../../../virt/kvm/kvm_main.o
In file included from include/linux/kvm_host.h:38:0,
                 from arch/x86/kvm/../../../virt/kvm/kvm_main.c:21:
include/linux/nitro_main.h:7:25: fatal error: linux/nitro.h: No such file or directory
 #include <linux/nitro.h>
                         ^
compilation terminated.

Any idea?

**Comment by shlomopongartz** [comment]
Hi,

I see that include/linux/linux/nitro.h is a soft link to ../../../nitro.h which is the kvm folter itself and this file is missing from there.
See also https://github.com/KVM-VMI/kvm/blob/master/include/linux/nitro.h

Best regards,

S.P.

**Comment by Wenzel** [comment]
Hi,
yes, mistake of mine.
Until recently, i was using a unique `nitro.h` in the root directory, and a symlink in both nitro and kvm subdirs.
I removed this file because nitro is full python now.
however, i was sure that i removed the symlink and replaced by the right file.
I just updated `master` on the kvm submodule, you should try and see if it fixes the issue.
