### ISSUE TITLE
Error when setting memory events with multiple vcpus - Invalid Argument

### ISSUE THREAD

**Issue by igor-benevides** [KVM-VMI/kvm-vmi#49]
I'm trying to set up some memory events on a guest machine, the events work without a problem with guests machines up to 4 vcpus, but with 5 or more some start to fail.
The following error occurs:
![image](https://user-images.githubusercontent.com/63594312/79128594-2c3e8b80-7d7a-11ea-9d0b-05cb681cb9a8.png)
I was trying to debug the arguments to see if the error was mine, but it only works if i tweak down the number of vcpus

Note: some of them work, but some don't.

**Comment by Wenzel** [comment]
Hi @IgorBenevides, thank you for testing KVM-VMI and the experimental Libvmi driver.

The error you mention is here in the code:
https://github.com/KVM-VMI/libvmi/blob/kvmi/libvmi/driver/kvm/kvm_events.c#L828

I suppose you are not dynamically adding more CPUs to the guest, which is not supported.
Also I can't recall implementing a hardcoded limit when I wrote the driver.

@IgorBenevides Can you share a code sample that reproduces the bug ?

cc @mdontu, @adlazar, any clue where it might come from ?

**Comment by adlazar** [comment]
You must have:

`if (kvm->libkvmi.kvmi_set_page_access(kvm->kvmi_dom, &gpa, &kvmi_access, 1))`

instead of:

`if (kvm->libkvmi.kvmi_set_page_access(kvm->kvmi_dom, &gpa, &kvmi_access, vmi->num_vcpus))`

The `kvmi_set_page_access()` function sends a VM command (affecting all vCPUs) with two arrays: one with guest addresses and one with the allowed access flags. The last parameter is the size of these two arrays.

**Comment by Wenzel** [comment]
I confirm that this fix is working.
thanks @adlazar.

@IgorBenevides can you open a PR on `kvmi` branch please ?

**Comment by IgorBenevides** [comment]
Awesome! Thanks for the attention, i'll open the PR.

**Comment by igor-benevides** [comment]
I can confirm that works aswell. The PR is created in the KVM-VMI/libvmi repo
